# Generated by Django 4.2.4 on 2023-09-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=100)),
            ],
        ),
    ]
