# Generated by Django 4.2.4 on 2023-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('battery_capcity', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
            ],
        ),
    ]
