# Generated by Django 4.2.4 on 2023-09-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_battery_capcity_phones_battery_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_produced', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=150)),
            ],
        ),
    ]
