# Generated by Django 4.2.4 on 2023-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
            ],
        ),
    ]
